services:
  db:
    image: mysql:8.0.32
    container_name: database
    command: --default-authentication-plugin=mysql_native_password
    entrypoint: ["/bin/bash", "/cleanup-entrypoint.sh"]
    environment: 
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3399:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backup_config/db_backups:/backups
      - ./backup_config/backup.sh:/backup.sh
      - ./backup_config/cleanup-entrypoint.sh:/cleanup-entrypoint.sh
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G 

  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6379:6379"

  scheduler:
    image: mcuadros/ofelia:latest
    container_name: scheduler
    volumes:
      - ./backup_config/config.ini:/etc/ofelia/config.ini
      - /var/run/docker.sock:/var/run/docker.sock   
      - ./backup_config/backup.sh:/backup.sh
    restart: unless-stopped
    environment:
      - OFELIA_CONFIG=/etc/ofelia/config.ini

volumes:
  mysql_data:
    external:
      name: personal_finance_data_volume
