SECTOR_MAP = {
    # ETF
    "Gold": "ETF",
    "Equity": "ETF",
    "Debt": "ETF",

    # Utilities
    "Power Infrastructure": "Utilities",
    "Power Transmission & Distribution": "Utilities",
    "Gas Distribution": "Utilities",
    "Power Trading & Consultancy": "Utilities",
    "Power Generation": "Utilities",
    "Renewable Energy": "Utilities",
    "Water Management": "Utilities",

    # Real Estate
    "Real Estate": "Real Estate",
    "Real Estate Development": "Real Estate",

    # Materials
    "Commodity Chemicals": "Materials",
    "Diversified Chemicals": "Materials",
    "Fertilizers & Agro Chemicals": "Materials",
    "Paints": "Materials",
    "Plastic Products": "Materials",
    "Specialty Chemicals": "Materials",
    "Cement": "Materials",
    "Packaging": "Materials",
    "Iron & Steel": "Materials",
    "Metals - Aluminium": "Materials",
    "Metals - Coke": "Materials",
    "Metals - Copper": "Materials",
    "Metals - Diversified": "Materials",
    "Metals - Lead": "Materials",
    "Metals - Iron": "Materials",
    "Mining - Coal": "Materials",
    "Mining - Copper": "Materials",
    "Mining - Diversified": "Materials",
    "Mining - Iron Ore": "Materials",
    "Mining - Manganese": "Materials",
    "Paper Products": "Materials",
    "Wood Products": "Materials",
    "Construction Materials": "Materials",
    "Steel": "Materials",

    # Information Technology
    "Communication & Networking": "Information Technology",
    "Electronic Equipments": "Information Technology",
    "Technology Hardware": "Information Technology",
    "IT Services & Consulting": "Information Technology",
    "Outsourced services": "Information Technology",
    "Software Services": "Information Technology",
    "Application Software": "Information Technology",

    # Industrials
    "Airlines": "Industrials",
    "Building Products - Ceramics": "Industrials",
    "Building Products - Glass": "Industrials",
    "Building Products - Granite": "Industrials",
    "Building Products - Laminates": "Industrials",
    "Building Products - Pipes": "Industrials",
    "Business Support Services": "Industrials",
    "Stationery": "Industrials",
    "Construction & Engineering": "Industrials",
    "Batteries": "Industrials",
    "Cables": "Industrials",
    "Electrical Components & Equipments": "Industrials",
    "Heavy Electrical Equipments": "Industrials",
    "Conglomerates": "Industrials",
    "Agricultural & Farm Machinery": "Industrials",
    "Heavy Machinery": "Industrials",
    "Industrial Machinery": "Industrials",
    "Rail": "Industrials",
    "Shipbuilding": "Industrials",
    "Tractors": "Industrials",
    "Trucks & Buses": "Industrials",
    "Employment Services": "Industrials",
    "Airports": "Industrials",
    "Dredging": "Industrials",
    "Logistics": "Industrials",
    "Ports": "Industrials",
    "Roads": "Industrials",
    "Renewable Energy Equipment & Services": "Industrials",
    "Building Products - Prefab Structures": "Industrials",
    "Commodities Trading": "Industrials",
    "Aerospace & Defense Equipments": "Industrials",
    "Diversified Support Services": "Industrials",
    "Construction Machinery & Heavy Transportation Equipment": "Industrials",
    "Data Processing & Outsourced Services": "Industrials",
    "Trading Companies & Distributors": "Industrials",
    "Industrial Machinery & Supplies & Components": "Industrials",

    # Health Care
    "Biotechnology": "Health Care",
    "Health Care Equipment & Supplies": "Health Care",
    "Hospitals & Diagnostic Centres": "Health Care",
    "Labs & Life Sciences Services": "Health Care",
    "Pharmaceuticals": "Health Care",

    # Financials
    "Private Banks": "Financials",
    "Public Banks": "Financials",
    "Asset Management": "Financials",
    "Investment Banking & Brokerage": "Financials",
    "Stock Exchanges & Ratings": "Financials",
    "Consumer Finance": "Financials",
    "Diversified Financials": "Financials",
    "Specialized Finance": "Financials",
    "Insurance": "Financials",
    "Home Financing": "Financials",
    "Payment Infrastructure": "Financials",
    "Asset Management & Custody Banks": "Financials",

    # Energy
    "Oil & Gas - Equipment & Services": "Energy",
    "Oil & Gas - Exploration & Production": "Energy",
    "Oil & Gas - Refining & Marketing": "Energy",
    "Oil & Gas - Storage & Transportation": "Energy",

    # Consumer Staples
    "Alcoholic Beverages": "Consumer Staples",
    "Soft Drinks": "Consumer Staples",
    "Tea & Coffee": "Consumer Staples",
    "Agro Products": "Consumer Staples",
    "FMCG - Foods": "Consumer Staples",
    "Packaged Foods & Meats": "Consumer Staples",
    "Seeds": "Consumer Staples",
    "Sugar": "Consumer Staples",
    "FMCG - Household Products": "Consumer Staples",
    "FMCG - Personal Products": "Consumer Staples",
    "FMCG - Tobacco": "Consumer Staples",
    "Food Distributors": "Consumer Staples",

    # Communication Services
    "Advertising": "Communication Services",
    "Cable & D2H": "Communication Services",
    "Movies & TV Serials": "Communication Services",
    "Publishing": "Communication Services",
    "Radio": "Communication Services",
    "Theatres": "Communication Services",
    "TV Channels & Broadcasters": "Communication Services",
    "Online Services": "Communication Services",
    "Telecom Equipments": "Communication Services",
    "Telecom Infrastructure": "Communication Services",
    "Telecom Services": "Communication Services",

    # Consumer Discretionary
    "Auto Parts": "Consumer Discretionary",
    "Tires & Rubber": "Consumer Discretionary",
    "Four Wheelers": "Consumer Discretionary",
    "Three Wheelers": "Consumer Discretionary",
    "Two Wheelers": "Consumer Discretionary",
    "Cycles": "Consumer Discretionary",
    "Education Services": "Consumer Discretionary",
    "Wellness Services": "Consumer Discretionary",
    "Hotels, Resorts & Cruise Lines": "Consumer Discretionary",
    "Restaurants & Cafes": "Consumer Discretionary",
    "Theme Parks & Gaming": "Consumer Discretionary",
    "Tour & Travel Services": "Consumer Discretionary",
    "Home Electronics & Appliances": "Consumer Discretionary",
    "Home Furnishing": "Consumer Discretionary",
    "Housewares": "Consumer Discretionary",
    "Retail - Apparel": "Consumer Discretionary",
    "Retail - Department Stores": "Consumer Discretionary",
    "Retail - Speciality": "Consumer Discretionary",
    "Apparel & Accessories": "Consumer Discretionary",
    "Footwear": "Consumer Discretionary",
    "Precious Metals, Jewellery & Watches": "Consumer Discretionary",
    "Textiles": "Consumer Discretionary",
    "Animation": "Consumer Discretionary",
}
